
# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    avoid_print: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true # fields don't change when they are declared with var, I'm learning ain't I?
    unnecessary_breaks: true # they flag unncecessary break statements!
    use_key_in_widget_constructors: true # the key allows to track and avoid any redundant glitch...
